### ISSUE TITLE
Migrate off of Node 11

### ISSUE THREAD

**Issue by fulldecent** [Zokrates/ZoKrates#457]
All of the supported NodeJS versions are listed at:

https://github.com/nodejs/Release (scroll down for the first timeline graphic)

This project uses Node 11, which is listed as "End-of-Life". This is a security risk because no security updates are being added to Node 11 and it is entirely unsupported by the vendor.

Current migration options are:

* Node 10, which is supported as LTS
* Node 12, which is incompatible with some of our Web3 dependencies

Recommending to switch to Node 10 at this time, and then a migration to Node 12 later.

# Work plan

- [ ] Update Travis and other CI scripts to test using Node 10
- [ ] Test locally using Node 10 (no code changes)
- [ ] If works then update documentation

**Comment by Schaeff** [comment]
Hi @fulldecent could you please edit the description with more details about the issue?

**Comment by fulldecent** [comment]
Updated
