### ISSUE TITLE
Clarify project scope: Test for production

### ISSUE THREAD

**Issue by fulldecent** [Zokrates/ZoKrates#649]
There is a strong caveat in the README.md:

> This is a proof-of-concept implementation. It has not been tested for production.

---

I understand that production testing is a serious process. I would like to clarify that this project is open to receiving assistance with security audit and testing for production use cases.

Because ZoKrates is getting built-in for more and more important projects -- I think resources will be available as needed.

---

# Work plan

- [ ] Create a project: "Production testing" at https://github.com/Zokrates/ZoKrates/projects
- [ ] Add columns: Discussion, Ready to start, In progress, Done
- [ ] Add note to Discussion: "This list is incomplete"
- [ ] Update README.md to say:
  > This is a proof-of-concept implementation. See [our plan to harden and test for production use cases](link).

That's the whole plan.

I'd create the project myself but I don't have write access here.
